import "@/scss/helpers/reset.scss"
import "@/scss/global.scss"

import NavigationBar from '@/components/globalComponents/NavigationBar'
import type { Metadata } from 'next'
import { Nunito, Poppins } from 'next/font/google'
import Footer from "@/components/globalComponents/Footer"

export const nunito = Nunito({
  subsets: ['latin'],
  variable: "--font-nunito",
})

export const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ['latin'],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pl" className={`${nunito.variable} ${poppins.variable}`}>
      <body>
        <header className="container">
          <NavigationBar />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
